project:
  type: website
  output-dir: docs
  
website:
  title: "Moise Dzogolo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - research.qmd
      - text: "EPPS 6302"
        menu:
          - href: Assignment 1.qmd
            text: "Assignment #1"

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

