project:
  type: website
  output-dir: docs
  
website:
  title: "Moise Dzogolo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - text: "Assignments"
        menu: 
          - assignment.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

