---
title: "Moise Dzogolo"
---

### About Moise Dzogolo

Welcome to the official website of Moise Dzogolo, a dedicated academioc and experienced professional committed to the intersection of public service and academia.

**Moise Dzogolo** is currently pursuing his Ph.D. in Public and Nonprofit Management at the University of Texas at Dallas, where he also serves as a Teaching Assistant. His academic journey is rooted in a strong foundation in Political Science and Urban Planning, coupled with some experience in local government.

**Professional Background:** Moise's professional career began in local government, where he worked as a City Planner. In this role, he reviewed applications for development and land use changes, ensuring that urban growth aligned with community needs and regulatory standards. His expertise was further showcased when he spearheaded a parking proposal project for townhomes, a strategic initiative presented to the Planning and Zoning Commission aimed at alleviating street congestion in residential areas.

**Teaching Experience:** With nearly half a decade of teaching experience, Moise has demonstrated a passion for education across various roles. He has tutored undergraduate students in subjects such as Statistics and Algebra, laying a solid foundation for their academic success. At the graduate level, he has served as a Teaching Assistant for courses including Government Financial Management, Introduction to Public Management, and Public Organization Management. His responsibilities in these roles extended beyond the classroom, where he developed study materials, crafted PowerPoint presentations, designed exam questions, and led review sessions to ensure students' comprehensive understanding of the subject matter.

Moise’s commitment to education is perhaps best exemplified in his work as an instructor. He successfully developed and taught an Urban Planning and Policy class for undergraduate students, combining his practical experience with academic rigor to deliver a course that was both insightful and impactful.

**Contact Information:** For academic inquiries or professional opportunities, please reach out to Moise Dzogolo at mmd220000\@utdallas.edu.

Moise Dzogolo's blend of academic expertise and practical experience makes him a valuable asset to both the academic community and the public sector, where his insights continue to influence future leaders and policymakers.
